"""initial_schema

Revision ID: 05fa35fbe2b7
Revises: 
Create Date: 2026-04-02 20:44:14.532526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05fa35fbe2b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('media_item',
    sa.Column('media_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_table('source',
    sa.Column('source_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('consumption_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('date_consumed', sa.Date(), nullable=False),
    sa.Column('time_consumed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_item.media_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('friendship',
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_friended', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('friend_id', 'user_id')
    )
    op.create_table('genre_similarity',
    sa.Column('genre_id_1', sa.Integer(), nullable=False),
    sa.Column('genre_id_2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id_1'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['genre_id_2'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('genre_id_1', 'genre_id_2')
    )
    op.create_table('goal',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('media_item_genre',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media_item.media_id'], ),
    sa.PrimaryKeyConstraint('media_id', 'genre_id')
    )
    op.create_table('media_item_source',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_item.media_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], ),
    sa.PrimaryKeyConstraint('media_id', 'source_id')
    )
    op.create_table('wrapped_report',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('most_used_media', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal'], ['goal.goal_id'], ),
    sa.ForeignKeyConstraint(['most_used_media'], ['media_item.media_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wrapped_report')
    op.drop_table('media_item_source')
    op.drop_table('media_item_genre')
    op.drop_table('goal')
    op.drop_table('genre_similarity')
    op.drop_table('friendship')
    op.drop_table('consumption_log')
    op.drop_table('user')
    op.drop_table('source')
    op.drop_table('media_item')
    op.drop_table('genre')
    # ### end Alembic commands ###
