"""initial_schema

Revision ID: 1ea509fcc3d4
Revises: 
Create Date: 2026-04-01 21:28:22.487674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea509fcc3d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_item',
    sa.Column('media_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('date_consumed', sa.Date(), nullable=False),
    sa.Column('time_consumed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('media_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_item')
    # ### end Alembic commands ###
