#!/usr/bin/env python3
"""
Seed script: inserts genres, media items, and genre associations.
All other data (users, logs, friendships, etc.) is generated by users.

Run from project root:
    python scripts/seed/seed.py

Or via the backend venv:
    backend/venv/bin/python scripts/seed/seed.py
"""

import json
import os
import sys

try:
    import psycopg
except ImportError:
    print("psycopg not found. Activate the backend venv first:")
    print("  source backend/venv/bin/activate")
    sys.exit(1)

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

SEED_FILE = os.path.join(os.path.dirname(__file__), "seed.json")
ENV_FILE = os.path.join(os.path.dirname(__file__), "../../backend/.env")

if load_dotenv:
    load_dotenv(ENV_FILE)

db_url = os.getenv(
    "DATABASE_URL",
    "postgresql+psycopg://mmj_user:mmj_password@localhost:5432/mymediajournal",
)
db_url = db_url.replace("postgresql+psycopg://", "postgresql://")

with open(SEED_FILE) as f:
    seed = json.load(f)

with psycopg.connect(db_url) as conn:
    with conn.cursor() as cur:

        for g in seed["genres"]:
            cur.execute(
                "INSERT INTO genre (genre_id, title) VALUES (%s, %s) ON CONFLICT DO NOTHING",
                (g["genre_id"], g["title"]),
            )
        print(f"✓ {len(seed['genres'])} genres")

        for m in seed["media_items"]:
            cur.execute(
                "INSERT INTO media_item (media_id, title, media_type) VALUES (%s, %s, %s) ON CONFLICT DO NOTHING",
                (m["media_id"], m["title"], m["media_type"]),
            )
        print(f"✓ {len(seed['media_items'])} media items")

        for mg in seed["media_item_genres"]:
            cur.execute(
                "INSERT INTO media_item_genre (media_id, genre_id) VALUES (%s, %s) ON CONFLICT DO NOTHING",
                (mg["media_id"], mg["genre_id"]),
            )
        print(f"✓ {len(seed['media_item_genres'])} genre associations")

        # Reset sequences so new inserts don't collide
        for table, col in [("genre", "genre_id"), ("media_item", "media_id")]:
            cur.execute(
                f"SELECT setval(pg_get_serial_sequence('{table}', '{col}'), "
                f"COALESCE(MAX({col}), 1)) FROM {table}"
            )

    conn.commit()

print("\nSeeding complete!")
